import { parseAllure } from 'allure-js-parser';
import { createResTest, fixResult } from '../../cy-helper/utils';

describe('run one test', () => {
  const storeResDir = createResTest(__filename);

  it(`check ${storeResDir}`, async () => {
    const results = parseAllure(storeResDir);
    const resFixed = fixResult(results);

    expect(resFixed).toEqual([
      {
        attachments: [
          {
            name: 'test simple -- after all hook generateReport (failed).png',
            source: 'source.png',
            type: 'image/png',
          },
          {
            name: 'one.cy.ts.mp4',
            source: 'source.mp4',
            type: 'video/mp4',
          },
        ],
        descriptionHtml: 'integration/e2e/one.cy.ts',
        fullName: 'suite with one test test simple',
        historyId: 'no',
        labels: [
          {
            name: 'package',
            value: 'suite with one test',
          },
          {
            name: 'parentSuite',
            value: 'suite with one test',
          },
          {
            name: 'path',
            value: 'integration/e2e/one.cy.ts',
          },
          {
            name: 'tag',
            value: 'BEFOREEACH',
          },
        ],
        links: [],
        name: 'test simple',
        parameters: [],
        parent: {
          afters: [],
          befores: [
            {
              attachments: [],
              name: '"before all" hook',
              parameters: [],
              stage: 'finished',
              start: 1323475200000,
              status: 'passed',
              statusDetails: {},
              steps: [
                {
                  attachments: [],
                  name: 'Coverage: Reset [@cypress/code-coverage]',
                  parameters: [],
                  stage: 'pending',
                  start: 1323475200000,
                  status: 'passed',
                  statusDetails: {},
                  steps: [],
                  stop: 1323475200011,
                },
              ],
              stop: 1323460800010,
            },
            {
              attachments: [],
              name: '"before all" hook',
              parameters: [],
              stage: 'finished',
              start: 1323475200000,
              status: 'passed',
              statusDetails: {},
              steps: [],
              stop: 1323460800010,
            },
          ],
          name: 'suite with one test',
          uuid: 'no',
        },
        stage: 'finished',
        start: 1323475200000,
        status: 'passed',
        statusDetails: {},
        steps: [
          {
            attachments: [],
            name: '"before each" hook: Register allure test',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [
              {
                attachments: [],
                name: 'log: log, Registered allureAdapterSetup',
                parameters: [],
                stage: 'pending',
                start: 1323475200000,
                status: 'passed',
                statusDetails: {},
                steps: [],
                stop: 1323475200011,
              },
            ],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: '"before each" hook',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: '"before each" hook',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [
              {
                attachments: [],
                name: 'log: HELLO)',
                parameters: [],
                stage: 'pending',
                start: 1323475200000,
                status: 'passed',
                statusDetails: {},
                steps: [],
                stop: 1323475200011,
              },
            ],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: 'assert: expected **0** to equal **0**',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: 'route: undefined',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: 'visit: mytest.com',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: 'get: body',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: 'my step',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [
              {
                attachments: [
                  {
                    name: 'afterScreen.png',
                    source: '4305ae20-70b7-57d3-b7b1-0f0659af2f9e-attachment.png',
                    type: 'image/png',
                  },
                ],
                name: 'screenshot: afterScreen',
                parameters: [],
                stage: 'pending',
                start: 1323475200000,
                status: 'passed',
                statusDetails: {},
                steps: [],
                stop: 1323475200011,
              },
            ],
            stop: 1323475200011,
          },
        ],
        stop: 1323460800010,
        uuid: 'no',
      },
      {
        attachments: [
          {
            name: 'one.cy.ts.mp4',
            source: 'source.mp4',
            type: 'video/mp4',
          },
        ],
        descriptionHtml: 'integration/e2e/one.cy.ts',
        fullName: 'suite with one test #2',
        historyId: 'no',
        labels: [
          {
            name: 'package',
            value: 'suite with one test',
          },
          {
            name: 'parentSuite',
            value: 'suite with one test',
          },
          {
            name: 'path',
            value: 'integration/e2e/one.cy.ts',
          },
          {
            name: 'tag',
            value: 'BEFOREEACH',
          },
          {
            name: 'tag',
            value: 'My',
          },
        ],
        links: [],
        name: '#2',
        parameters: [],
        parent: {
          afters: [],
          befores: [
            {
              attachments: [],
              name: '"before all" hook',
              parameters: [],
              stage: 'finished',
              start: 1323475200000,
              status: 'passed',
              statusDetails: {},
              steps: [
                {
                  attachments: [],
                  name: 'Coverage: Reset [@cypress/code-coverage]',
                  parameters: [],
                  stage: 'pending',
                  start: 1323475200000,
                  status: 'passed',
                  statusDetails: {},
                  steps: [],
                  stop: 1323475200011,
                },
              ],
              stop: 1323460800010,
            },
            {
              attachments: [],
              name: '"before all" hook',
              parameters: [],
              stage: 'finished',
              start: 1323475200000,
              status: 'passed',
              statusDetails: {},
              steps: [],
              stop: 1323460800010,
            },
          ],
          name: 'suite with one test',
          uuid: 'no',
        },
        stage: 'finished',
        start: 1323475200000,
        status: 'passed',
        statusDetails: {},
        steps: [
          {
            attachments: [],
            name: '"before each" hook: Register allure test',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [
              {
                attachments: [],
                name: 'log: log, Registered allureAdapterSetup',
                parameters: [],
                stage: 'pending',
                start: 1323475200000,
                status: 'passed',
                statusDetails: {},
                steps: [],
                stop: 1323475200011,
              },
            ],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: '"before each" hook',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: '"before each" hook',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [
              {
                attachments: [],
                name: 'log: HELLO)',
                parameters: [],
                stage: 'pending',
                start: 1323475200000,
                status: 'passed',
                statusDetails: {},
                steps: [],
                stop: 1323475200011,
              },
            ],
            stop: 1323475200011,
          },
        ],
        stop: 1323460800010,
        uuid: 'no',
      },
      {
        attachments: [
          {
            name: 'suite with one test -- #1 test fail (failed).png',
            source: 'source.png',
            type: 'image/png',
          },
          {
            name: 'one.cy.ts.mp4',
            source: 'source.mp4',
            type: 'video/mp4',
          },
        ],
        descriptionHtml: 'integration/e2e/one.cy.ts',
        fullName: 'suite with one test #1 test fail',
        historyId: 'no',
        labels: [
          {
            name: 'package',
            value: 'suite with one test',
          },
          {
            name: 'parentSuite',
            value: 'suite with one test',
          },
          {
            name: 'path',
            value: 'integration/e2e/one.cy.ts',
          },
          {
            name: 'tag',
            value: 'BEFOREEACH',
          },
        ],
        links: [],
        name: '#1 test fail',
        parameters: [],
        parent: {
          afters: [],
          befores: [
            {
              attachments: [],
              name: '"before all" hook',
              parameters: [],
              stage: 'finished',
              start: 1323475200000,
              status: 'passed',
              statusDetails: {},
              steps: [
                {
                  attachments: [],
                  name: 'Coverage: Reset [@cypress/code-coverage]',
                  parameters: [],
                  stage: 'pending',
                  start: 1323475200000,
                  status: 'passed',
                  statusDetails: {},
                  steps: [],
                  stop: 1323475200011,
                },
              ],
              stop: 1323460800010,
            },
            {
              attachments: [],
              name: '"before all" hook',
              parameters: [],
              stage: 'finished',
              start: 1323475200000,
              status: 'passed',
              statusDetails: {},
              steps: [],
              stop: 1323460800010,
            },
          ],
          name: 'suite with one test',
          uuid: 'no',
        },
        stage: 'finished',
        start: 1323475200000,
        status: 'failed',
        statusDetails: {
          message: 'Timed out retrying after 4000ms: Expected to find element: `div:eq(2)`, but never found it.',
          trace:
            'AssertionError: Timed out retrying after 4000ms: Expected to find element: `div:eq(2)`, but never found it.\n    at Context.eval (webpack://@mmisty/cypress-allure-adapter/./integration/e2e/one.cy.ts:24:44)',
        },
        steps: [
          {
            attachments: [],
            name: '"before each" hook: Register allure test',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [
              {
                attachments: [],
                name: 'log: log, Registered allureAdapterSetup',
                parameters: [],
                stage: 'pending',
                start: 1323475200000,
                status: 'passed',
                statusDetails: {},
                steps: [],
                stop: 1323475200011,
              },
            ],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: '"before each" hook',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: '"before each" hook',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [
              {
                attachments: [],
                name: 'log: HELLO)',
                parameters: [],
                stage: 'pending',
                start: 1323475200000,
                status: 'passed',
                statusDetails: {},
                steps: [],
                stop: 1323475200011,
              },
            ],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: 'assert: expected **0** to equal **0**',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: 'route: undefined',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: 'visit: mytest.com',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: 'get: div',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [
              {
                attachments: [],
                name: 'assert: expected **[ <div>, 1 more... ]** to exist in the DOM',
                parameters: [],
                stage: 'pending',
                start: 1323475200000,
                status: 'passed',
                statusDetails: {},
                steps: [],
                stop: 1323475200011,
              },
            ],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: 'myLog: log task',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: 'task: log, log task',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'passed',
            statusDetails: {},
            steps: [],
            stop: 1323475200011,
          },
          {
            attachments: [],
            name: 'get: div:eq(2)',
            parameters: [],
            stage: 'pending',
            start: 1323475200000,
            status: 'failed',
            statusDetails: {},
            steps: [
              {
                attachments: [],
                name: 'assert: expected **div:eq(2)** not to exist in the DOM',
                parameters: [],
                stage: 'pending',
                start: 1323475200000,
                status: 'passed',
                statusDetails: {},
                steps: [],
                stop: 1323475200011,
              },
              {
                attachments: [],
                name: 'assert: expected **null** to exist',
                parameters: [],
                stage: 'pending',
                start: 1323475200000,
                status: 'failed',
                statusDetails: {},
                steps: [],
                stop: 1323475200011,
              },
            ],
            stop: 1323475200011,
          },
        ],
        stop: 1323460800010,
        uuid: 'no',
      },
    ]);
  });
});
